#!/usr/bin/env node
/**
 * prepare-assets.js
 *
 * Copies wordlist .txt files from scripts/wordlists/ into app/assets/ for bundling
 * with the React Native app, and generates a TypeScript module embedding the wordlists.
 *
 * Usage: node scripts/prepare-assets.js
 * (run from app/ directory)
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const WORDLISTS_SRC = path.join(ROOT_DIR, '..', 'scripts', 'wordlists');

// Output to both the generic assets dir and Android's assets dir
const ASSETS_DIR = path.join(ROOT_DIR, 'assets');
const ANDROID_ASSETS_DIR = path.join(ROOT_DIR, 'android', 'app', 'src', 'main', 'assets');

const WORDLISTS_DEST = path.join(ASSETS_DIR, 'wordlists');
const ANDROID_WORDLISTS_DEST = path.join(ANDROID_ASSETS_DIR, 'wordlists');

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, {recursive: true});
  }
}

function copyWordlists() {
  ensureDir(WORDLISTS_DEST);
  ensureDir(ANDROID_WORDLISTS_DEST);

  const files = fs.readdirSync(WORDLISTS_SRC).filter(f => f.endsWith('.txt') && !f.startsWith('joukahainen'));
  console.log(`Copying ${files.length} wordlist file(s)...`);

  for (const file of files) {
    const srcPath = path.join(WORDLISTS_SRC, file);
    fs.copyFileSync(srcPath, path.join(WORDLISTS_DEST, file));
    fs.copyFileSync(srcPath, path.join(ANDROID_WORDLISTS_DEST, file));
    console.log(`  ${file}`);
  }

  // Generate a JS module that embeds wordlists for reliable Metro bundling
  const generatedDir = path.join(ROOT_DIR, 'src', 'generated');
  ensureDir(generatedDir);

  const wordlistEntries = [];
  for (const file of files) {
    const srcPath = path.join(WORDLISTS_SRC, file);
    const words = fs.readFileSync(srcPath, 'utf8')
      .split('\n')
      .map(w => w.trim())
      .filter(w => w.length > 0);
    const key = file.replace('.txt', '');
    wordlistEntries.push(`  '${key}': ${JSON.stringify(words)}`);
  }

  const moduleContent = `// Auto-generated by scripts/prepare-assets.js — do not edit manually
const WORDLISTS: Record<string, string[]> = {\n${wordlistEntries.join(',\n')}\n};\n\nexport default WORDLISTS;\n`;
  fs.writeFileSync(path.join(generatedDir, 'wordlists.ts'), moduleContent, 'utf8');
  console.log('  Generated src/generated/wordlists.ts');
}

function main() {
  console.log('Preparing app assets...\n');

  if (!fs.existsSync(WORDLISTS_SRC)) {
    console.error(`ERROR: Wordlists directory not found: ${WORDLISTS_SRC}`);
    process.exit(1);
  }

  copyWordlists();
  console.log('\nDone!');
}

main();
