#!/usr/bin/env node
/**
 * prepare-assets.js
 *
 * Copies wordlist .txt files from scripts/wordlists/ into app/assets/ for bundling
 * with the React Native app, generates a TypeScript module embedding the wordlists,
 * and encrypts last_words files into a separate TS module.
 *
 * Usage: node scripts/prepare-assets.js
 * (run from app/ directory)
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ENCRYPTION_KEY = '4f6b7a9c2e1d8f3a5b0c7d4e9f2a1b6c8d3e0f5a7b9c4d2e1f8a3b6c0d5e7f9a';
const ALGORITHM = 'aes-256-cbc';

const ROOT_DIR = path.resolve(__dirname, '..');
const WORDLISTS_SRC = path.join(ROOT_DIR, '..', 'scripts', 'wordlists');
const LAST_WORDS_SRC = path.join(ROOT_DIR, '..', 'scripts', 'last_words');

// Output to both the generic assets dir and Android's assets dir
const ASSETS_DIR = path.join(ROOT_DIR, 'assets');
const ANDROID_ASSETS_DIR = path.join(ROOT_DIR, 'android', 'app', 'src', 'main', 'assets');

const WORDLISTS_DEST = path.join(ASSETS_DIR, 'wordlists');
const ANDROID_WORDLISTS_DEST = path.join(ANDROID_ASSETS_DIR, 'wordlists');

function encrypt(text) {
  const iv = crypto.randomBytes(16);
  const key = Buffer.from(ENCRYPTION_KEY, 'hex');
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  let encrypted = cipher.update(text, 'utf8', 'base64');
  encrypted += cipher.final('base64');
  return iv.toString('base64') + ':' + encrypted;
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, {recursive: true});
  }
}

function copyWordlists() {
  ensureDir(WORDLISTS_DEST);
  ensureDir(ANDROID_WORDLISTS_DEST);

  const files = fs.readdirSync(WORDLISTS_SRC).filter(f => f.endsWith('.txt') && !f.startsWith('joukahainen'));
  console.log(`Copying ${files.length} wordlist file(s)...`);

  for (const file of files) {
    const srcPath = path.join(WORDLISTS_SRC, file);
    fs.copyFileSync(srcPath, path.join(WORDLISTS_DEST, file));
    fs.copyFileSync(srcPath, path.join(ANDROID_WORDLISTS_DEST, file));
    console.log(`  ${file}`);
  }

  // Generate a JS module that embeds wordlists for reliable Metro bundling
  const generatedDir = path.join(ROOT_DIR, 'src', 'generated');
  ensureDir(generatedDir);

  const wordlistEntries = [];
  for (const file of files) {
    const srcPath = path.join(WORDLISTS_SRC, file);
    const words = fs.readFileSync(srcPath, 'utf8')
      .split('\n')
      .map(w => w.trim())
      .filter(w => w.length > 0);
    const key = file.replace('.txt', '');
    wordlistEntries.push(`  '${key}': ${JSON.stringify(words)}`);
  }

  const moduleContent = `// Auto-generated by scripts/prepare-assets.js — do not edit manually
const WORDLISTS: Record<string, string[]> = {\n${wordlistEntries.join(',\n')}\n};\n\nexport default WORDLISTS;\n`;
  fs.writeFileSync(path.join(generatedDir, 'wordlists.ts'), moduleContent, 'utf8');
  console.log('  Generated src/generated/wordlists.ts');
}

function main() {
  console.log('Preparing app assets...\n');

  if (!fs.existsSync(WORDLISTS_SRC)) {
    console.error(`ERROR: Wordlists directory not found: ${WORDLISTS_SRC}`);
    process.exit(1);
  }

  copyWordlists();
  console.log('');
  encryptLastWords();
  console.log('\nDone!');
}

function encryptLastWords() {
  const generatedDir = path.join(ROOT_DIR, 'src', 'generated');
  ensureDir(generatedDir);

  if (!fs.existsSync(LAST_WORDS_SRC)) {
    console.log('No last_words directory found, skipping.');
    return;
  }

  const files = fs.readdirSync(LAST_WORDS_SRC).filter(f => f.endsWith('.txt'));
  console.log(`Encrypting ${files.length} last_words file(s)...`);

  const entries = [];
  for (const file of files) {
    const srcPath = path.join(LAST_WORDS_SRC, file);
    const content = fs.readFileSync(srcPath, 'utf8');
    const encrypted = encrypt(content);
    const key = file.replace('.txt', '');
    entries.push(`  '${key}': '${encrypted}'`);
    console.log(`  ${file}`);
  }

  const moduleContent = `// Auto-generated by scripts/prepare-assets.js — do not edit manually
// Encrypted last_words content (AES-256-CBC, format: base64(iv):base64(ciphertext))
const LAST_WORDS_ENCRYPTED: Record<string, string> = {\n${entries.join(',\n')}\n};\n\nexport default LAST_WORDS_ENCRYPTED;\n`;
  fs.writeFileSync(path.join(generatedDir, 'lastWords.ts'), moduleContent, 'utf8');
  console.log('  Generated src/generated/lastWords.ts');
}

main();
